version: '3.9'

services:
  mysql:
    image: mysql:latest
    container_name: retfig-db
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: retfig
      MYSQL_USER: retfig
      MYSQL_PASSWORD: mypassword
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql

  retfig:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: retfig
    ports:
      - "8080:8080"
    environment:
      RETFIG_MYSQL_HOST: retfig-db
      RETFIG_MYSQL_USER: retfig
      RETFIG_MYSQL_PASSWORD: mypassword
      RETFIG_MYSQL_DATABASE_NAME: retfig
    depends_on:
      - mysql

volumes:
  mysql-data:
